version: "3"
services:
  apdev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: apdev:1
    network_mode: host
    container_name: apdev
    environment:
      - ENABLE_PROXY=true
    volumes:
      - ./apisix:/usr/local/apisix
      - ./plugins/axzarbac:/usr/local/apisix/apisix/plugins/axzarbac
      - ./plugins/axzarbac.lua:/usr/local/apisix/apisix/plugins/axzarbac.lua
      - ./conf/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./conf/debug.yaml:/usr/local/apisix/conf/debug.yaml
      - ./axza:/usr/local/apisix/axza # for proxy-cache module
      - ./logs:/usr/local/apisix/logs #local logs storage
      - ./tmp:/tmp # for proxy-cache module
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - net-dev
networks:
  net-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.12.0.0/16



# useradd anobody -u 65534 #create alpine nobody if not exist
# chown 65534 /data/prometheus  # add permission to folder
# docker-compose up -d apdev
# docker-compose up -d etcd
# docker exec -it apdev sh


# docker run -p 11000:80  --network=host  -it -v /data/dc:/data --name ori ori:1.0 /bin/bash